[theme]
# Tema Dark Minimalista - Brazilian License Plate Recognition
base = "dark"
primaryColor = "#667eea"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d29"
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
runOnSave = true
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[runner]
fastReruns = true
magicEnabled = true

